version: '3'

services:
  terminal:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.devops
    image: georgeyord/terminal:latest
    container_name: terminal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./data/myhome:/myhome
    ports:
      - "8080:8080"
    # Override `command` to run the terminal without `byobu` ()enabled by default
    command:
      - /bin/zsh
    # environment:
      # Setup a custom user
      # Use `id` in host machine to find the UID/GID you use in host machine
      # USER_ID: 9999 # Required to use a custom user
      # GROUP_ID: 9999 # Optional, set user group id
      # USER_NAME: myuser # Optional, set desired name
      # USER_HOME: /custom_home # Optional, set a custom home path
      # SUDO_WITHOUT_PASSWORD: "false" # Optional, toggle sudo access without password

      # Set preferred Gotty options: https://github.com/yudai/gotty#options
      # GOTTY_OPTIONS:
      # Set a custom timezone
      # TZ: "Europe/Berlin"
      # Enable script verbose logs
      # DEBUG_FLAG: "true"
